---
version: 2
checks:
  file-lines:
    config:
      threshold: 400
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 35
  method-lines:
    config:
      threshold: 100
  return-statements:
    config:
      threshold: 10
plugins:
  # stylelint:
  #   enabled: true
  #   config:
  #     config: .stylelintrc.json
  #   exclude_patterns:
  #     - 'static/css'
  #     - 'static/admin'
  #     - 'assets/styles/libs/'
  #     - 'assets/styles/style.css'
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 350
  eslint:
    enabled: true
    channel: eslint-7
    config:
      config: .eslintrc.js
    exclude_patterns:
      - 'src/service-worker.js'
  fixme:
    enabled: true
    exclude_patterns:
      - 'assets/img/'
exclude_patterns:
  - 'assets/styles/libs/'
  - 'src/store/modules/load-balancing.module.js'
