export default {
  ApiUrl: process.env.VUE_APP_FTL_API_URL,
  AppUrl: process.env.VUE_APP_FTL_URL,
  CLIENT_ID: process.env.VUE_APP_FTL_COGNITO_CLIENT_ID,
  APP_DOMAIN: process.env.VUE_APP_FTL_COGNITO_APP_DOMAIN,
  REDIRECT_URI: process.env.VUE_APP_FTL_COGNITO_REDIRECT_URI,
  USERPOOL_ID: process.env.VUE_APP_FTL_COGNITO_USERPOOL_ID,
  REDIRECT_URI_SIGNOUT: process.env.VUE_APP_FTL_COGNITO_REDIRECT_URI_SIGNOUT,
  REDIRECT_URI_RESET_PASS: process.env.VUE_APP_FTL_RESET_PASSWORD_REDIRECT_URI,
  VUE_APP_FTL_REDIRECT_URI_PROTOCOL:
    process.env.VUE_APP_FTL_REDIRECT_URI_PROTOCOL,
  VUE_APP_FTL_ACTIVITY_IDLE_TTL: process.env.VUE_APP_FTL_ACTIVITY_IDLE_TTL,
  VUE_APP_FTL_ACTIVITY_ALERT_TTL: process.env.VUE_APP_FTL_ACTIVITY_ALERT_TTL,
};
